apiVersion: v1
kind: Service
metadata:
  name: clockbucks-api-service
  namespace: clockbucks
  labels:
    app: clockbucks-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: clockbucks-api
---
apiVersion: v1
kind: Service
metadata:
  name: clockbucks-api-nodeport
  namespace: clockbucks
  labels:
    app: clockbucks-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: clockbucks-api
